nohup: ignoring input
Traceback (most recent call last):
  File "./tools/train.py", line 13, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/home/lixinhao/vss/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/lixinhao/vss/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/home/lixinhao/vss/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/lixinhao/vss/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/home/lixinhao/vss/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/lixinhao/vss/mmseg/models/decode_heads/__init__.py", line 16, in <module>
    from .point_head import PointHead
  File "/home/lixinhao/vss/mmseg/models/decode_heads/point_head.py", line 6, in <module>
    from mmcv.ops import point_sample
  File "/home/lixinhao/anaconda3/envs/nvsss/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/lixinhao/anaconda3/envs/nvsss/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/lixinhao/anaconda3/envs/nvsss/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/lixinhao/anaconda3/envs/nvsss/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Traceback (most recent call last):
  File "/home/lixinhao/anaconda3/envs/nvsss/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lixinhao/anaconda3/envs/nvsss/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lixinhao/anaconda3/envs/nvsss/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/lixinhao/anaconda3/envs/nvsss/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/lixinhao/anaconda3/envs/nvsss/bin/python', '-u', './tools/train.py', '--local_rank=0', 'local_configs/mrcfa/B2/mrcfa.b2.480x480.vspw2_hypercorr.160k.py', '--launcher', 'pytorch', '--work-dir', 'model_path/vspw2/work_dirs_4g_b4']' returned non-zero exit status 1.
